### ISSUE TITLE
Webpage Tweaks to Mondoo Docs sidebar menu (Reference CLI Commands)

### ISSUE THREAD

**Issue by ehaselwanter** [mondoolabs/mondoo#72]
A bit about least surprise: The see also section on the bottom of https://docs.mondoo.io/references/cli/mondoo 

list all like I expect it

```
SEE ALSO#

mondoo client - Subcommand for managing service accounts
mondoo completion - Generate completion script
mondoo exec - Run a Mondoo query
mondoo migrate - Migrates Mondoo CLI configuration to the latest version
mondoo policy - Interact with policies
mondoo register - Registers Mondoo Client with Mondoo Platform
mondoo scan - Scans assets with one or more polices
mondoo serve - Start a Mondoo in background serve mode
mondoo shell - Interactive query shell
mondoo status - Verifies the access to Mondoo Cloud
mondoo unregister - Unregister Mondoo Client from Mondoo Platform
mondoo version - Displays the Mondoo Client version
```

The menu on the left:

- does not include all commands (at least shell is missing)
- is not in alphabetical order

<img width="261" alt="image" src="https://user-images.githubusercontent.com/18671/140488656-9ff586f6-5fb9-4022-a623-ccbec8fe0eee.png">

**Comment by chris-rock** [comment]
Thank you @ehaselwanter for reporting this issue, docs have been updated and improved to include all commands in the sidebar, see https://docs.mondoo.io/references/cli/mondoo

<img width="252" alt="Screenshot 2021-11-05 at 11 11 31" src="https://user-images.githubusercontent.com/1178413/140494621-2ed78d27-9078-47c4-afed-a31d0c4f93cb.png">
