### ISSUE TITLE
Docker Scan Information

### ISSUE THREAD

**Issue by mabunixda** [mondoolabs/mondoo#75]
**Is your feature request related to a problem? Please describe.**
When running a mondoo scan on a docker image with ```mondoo scan -t docker://....``` only the image id is reported/available. Also the platform is set to unknown.

![image](https://user-images.githubusercontent.com/1193145/141751837-592ce3ff-187c-4080-b30b-e58483b7c15a.png)

**Describe the solution you'd like**
I would love to see also to used image name - or the scan target name - in the reporting as another attribute in the report.
Also the platform information should be set!

**Comment by chris-rock** [comment]
@mabunixda Thank you for the feedback. We are going to fix this issue in one of our next releases.

**Comment by chris-rock** [comment]
We have fixed that in latest version, please re-open if you see cases where this is still happening
